CREATE DATABASE IF NOT EXISTS website;
FLUSH PRIVILEGES;
USE website;

CREATE TABLE IF NOT EXISTS users (
	name VARCHAR(32) NOT NULL,
	email VARCHAR(32) NOT NULL,
	password VARCHAR(512) NOT NULL,
	admin INT NOT NULL,
	communities VARCHAR(8192)
);

CREATE TABLE IF NOT EXISTS refresh_tokens (
	email VARCHAR(32) NOT NULL,
	JWT VARCHAR(256) NOT NULL
);

